### ISSUE TITLE
pred_* fails running basic example

### ISSUE THREAD

**Issue by allienu** [soodoku/ethnicolr#3]
After installing ethnicolr as described via pip (multiple systems attempted), using any pred method (i.e. anything other than census_ln) results in the following error through TensorFlow. This is following the exact code specified in the readme - create a list of dictionaries (3 names), convert this to a pandas DataFrame, and pass that (along with 'first' and/or 'last') to ethnicolr.{some method}

```
ethnicolr.pred_wiki_name(df, 'first', 'last')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/~/Library/Python/2.7/lib/python/site-packages/ethnicolr/pred_wiki_name.py", line 70, in pred_wiki_name
    model = load_model(MODEL)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 239, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 313, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 1214, in from_config
    model.add(layer)
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 442, in add
    layer(x)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 575, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/site-packages/keras/layers/embeddings.py", line 101, in build
    dtype=self.dtype)
  File "/usr/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 399, in add_weight
    constraint=constraint)
  File "/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 316, in variable
    v = tf.Variable(value, dtype=_convert_string_dtype(dtype), name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 289, in _init_from_args
    initial_value, name="initial_value", dtype=dtype)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 549, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("embedding_1/random_uniform:0", shape=(2260, 32), dtype=float32)'
```

**Comment by suriyan** [comment]
It seems there is the problem with newer version of Keras (> 2.0.5).

Please force the Keras version to 2.0.5 by the following command:-

```
pip install keras==2.0.5
```

Thanks!

**Comment by allienu** [comment]
That solves it. Thanks!
